stats4sd/aec_portfolio

- app/Http/Controllers/Admin/ProjectCrudController.php
- composer.json
- composer.lock
- public/assets/js/admin/forms/project_assess.js
- resources/views/vendor/backpack/crud/buttons/import-template.blade.php
- storage/debugbar/.gitignore
Fixes #2, #12 and #14 (typos and adding client-side validation).
> Typos and fixes

- app/Exports/OrganisationExport.php
- app/Http/Controllers/Admin/Operations/RedlineOperation.php
- app/Http/Controllers/Admin/OrganisationCrudController.php
- app/Http/Controllers/OrganisationController.php
- app/Models/PrincipleProject.php
- app/Models/RedLine.php
- config/backpack/base.php
- public/mix-manifest.json
- resources/js/radarChart.js
- resources/views/organisations/header.blade.php
- resources/views/organisations/portfolio.blade.php
- resources/views/organisations/portfolio/_keyIndicators.blade.php
- resources/views/organisations/portfolio/_principleByPrinciple.blade.php
- resources/views/organisations/portfolio/_redlines.blade.php
- resources/views/organisations/portfolio/_spiderChart.blade.php
- routes/backpack/custom.php
- webpack.mix.js
Adds a demo portfolio analysis dashboard, including:
Tab 1:
- a set of key summary stats;
- a spider chart of the portfolio average ratings
- tables showing:
- % of projects failing each redline
- % of projects marking each principle as na
Tab 2:
- a set of violin plots showing the distribution of ratings for each principle, for your organisation vs all projects in the platform;
Tab 3:
- a pair of tables showing the average rating for each principle, again comparing your organisation vs all projects in the platform.
*Note: The violin plots are generated using HighCharts and the Kernal Density Estimation Process linked below. This is *not* an endorsement of this methodology (as I haven't looked into exactly what it's doing!) but it's enough to get a visual sense of how we can visually …
> Dashboard Demo

- app/Http/Controllers/OrganisationMemberController.php
- app/Http/Requests/OrganisationMemberUpdateRequest.php
- resources/views/organisations/edit-members.blade.php
- resources/views/organisations/members.blade.php
A minor change for maintaining institutional users:
1. Institution Member CRUD, list view, remove Access Type, show Role
2. Institution Member CRUD, update view, update system role of existing user
> Maintain Institutional Users

- app/Models/Project.php
- fixes issue where new projects don't receive the organisation's existing Additional Criteria
> sync org's additional criteria to new projects:

- app/Http/Controllers/Admin/Operations/ImportOperation.php
- app/Http/Controllers/Admin/ProjectCrudController.php
- app/Http/Requests/ProjectRequest.php
- app/Imports/ProjectImport.php
- app/Imports/ProjectWorkbookImport.php
- app/Models/Portfolio.php
- app/Rules/UniqueProjectCode.php
- database/seeders/TestSeeder.php
Updates the project importer (fixes #28 , fixes #29 ).
Users can upload an Excel file of project/initiative information. The file data is validated against the same set of rules compared to adding records through the platform.  
- Previously, the user would select an organisation to import the data into. Now, the organsiation is automatically chosen as the "current" org (via the Session), and the user chooses which **portfolio** to import the data into. 
- This PR also adds proper validation, so now any validation errors are shown after the upload attempt.
- As part of this, I switched to use the `GeographicReach` enum class everywhere I could find (for consistency).
- I added a fix for the ProjectUniqueCode Rule, so that it now gets the organisation from the Session. 
- I also added a …
> Project importer

- app/Http/Controllers/Admin/Operations/RedlineOperation.php
- database/procedures/generate_dashboard_summary.sql
- package-lock.json
- package.json
- resources/js/components/MainDashboard.vue
Minor tweaks based on manual calculation checks.
> Calculation checks

- database/seeders/DatabaseSeeder.php
- database/seeders/ScoreTagsTableSeeder.php
- resources/js/components/PrincipleAssessmentModal.vue
- resources/sass/app.scss
This PR is submitted to fix issue #81.
Score tags can be showed in local env after importing score_tags records from demo_testing server.
> Add seeder file for table score_tags

- app/Http/Controllers/ProjectController.php
- app/Models/Assessment.php
- database/procedures/generate_dashboard_summary.sql
Adds check to allow control over whether or not we show the data for "other" institutions on the dashboard, based on the count of initiatives and institutions within the dataset resulting from the chosen filters. 
The exact required number of institutions / initiatives required will likely change, and for now this can be changed at `/database/procedures/generate_dashboad_summary.sql` line 261.
> Optimise anonymity check

- database/procedures/generate_dashboard_summary.sql
- resources/js/components/MainDashboard.vue
This PR is submitted to fix issues #70 and #84.
Screen shots for easy reference:
BEFORE:
Show 2 d.p. value for verification:
AFTER:
> Revise dashboard red flags summary

- routes/backpack/custom.php
This PR is submitted to fix issues #91 and #92.
> Fix Portfolio and Additional Assessment CRUD panels sometimes uses old page layout

- app/Exports/Assessment/AdditionalCriteriaExport.php
- app/Exports/Assessment/AssessmentExportWorkbook.php
Small PR to add the additional criteria data to the intitiative data export workbook. Uses the same format as the principle assessment. 
fixes #125
> Add additional assessment to export

- app/Exports/Assessment/AdditionalCriteriaExport.php
Quick fix and merge to support ongoing work with testers.
> fix additional_criteria_assessment

- app/Http/Controllers/Admin/PortfolioCrudController.php
- app/Http/Requests/PortfolioRequest.php
- database/migrations/2023_07_24_141002_update_portfolios_table.php
- resources/views/organisations/portfolios.blade.php
This PR updates portfolios by:
- adding a description
- removing geographic reach
fixes #161
> adds description and removes geographic reach

- resources/js/components/AgroecologicalPrinciplesAssessment.vue
This PR adds the initiative name as part of the title on the main assessment page
> adds initiative name on assessment page

- .env.example
- composer.json
- composer.lock
- config/logging.php
Minor config change to log errors to Laravel Flare
> setup flare logging

- database/seeders/TestSeeder.php
- resources/js/components/InitiativesList.vue
Part 2 of #199  (budget sorting)
> Budget checks

- app/Console/Kernel.php
Replaces day-name with a constant value that the Scheduler can recognise.
> replace string with day-of-week constant

- app/Http/Controllers/Admin/OrganisationCrudController.php
- resources/js/components/InstitutionSettings.vue
This PR
- brings back the currency field on the settings page
- set institution name as required on creation
> Fix default currency

- app/Http/Controllers/OrganisationController.php
- app/Models/Assessment.php
- database/procedures/generate_dashboard_summary.sql
- database/seeders/HelpTextEntrySeeder.php
- resources/js/components/InitiativeListCard.vue
- resources/js/components/InstitutionSettings.vue
- resources/js/components/MainDashboard.vue
- resources/views/organisations/portfolios.blade.php
- routes/backpack/custom.php
Minor fixes to address remaining presentation issues. Fixes #114; fixes #74. 
- Add page reload to institution settings if the has_additional_criteria is changed.
- Add additional criteria score to the initiatives card.
This is not a proper fix. A full fix needs some conceptualising of how to present the summary of initaitives at different stages of the process on the dashbaord - which is a possible task for V2.0. But this PR adds "# initiatives with failed red-flags".
> Admin updates

- resources/js/components/InitiativesList.vue
Publishing this minor feature update in advance of the longer, currency / budget filter updates
> add search by code directly to main

- database/procedures/generate_dashboard_summary.sql
@dan-tang-ssd  - I have created 2 PRs - to merge this directly into main as well as dev, so we can publish this hotfix without waiting to review and publish the EUR currency conversion.
> re-enable code to hide 'other' results - Hotfix deploy straight to main

- app/Models/Organisation.php
This PR is submitted to fix issue #281 
This PR contains below change:
1. Check if email address is empty before sending invite. If email is empty, skip to next email
Performed testing with positive result in local env.
> Fix Invite Issue

- app/Http/Controllers/Admin/ProjectCrudController.php
- app/Models/Organisation.php
This PR is submitted for live env deployment.
It contains below bug fix for invites issue:
1. Check if email address is empty before sending invite. If email is empty, skip to next email
> Live Env Deployment

- app/Http/Controllers/Admin/ProjectCrudController.php
This PR is submitted to fix #165 
It is now ready for review.
---
I did checking for below items, finally I use HTML 5 native date as solution
- check filament document
- find filament plugins
- find alternative way: HTML 5 native date
---
Google search result:
HTML <input type="date">
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_date
why cant datepicker fields be manually entered? #363
https://github.com/filamentphp/filament/discussions/363
> Enhance Date Input

- app/Http/Controllers/ProjectController.php
- app/Http/Kernel.php
- app/Http/Middleware/SetProjectInSession.php
- resources/js/components/InitiativeListCard.vue
- resources/js/components/InitiativesList.vue
- resources/views/projects/index.blade.php
- resources/views/projects/show.blade.php
- routes/backpack/custom.php
- routes/web.php
This PR is submitted to fix #169 
---
> Add Project Anchor

- app/Http/Controllers/ProjectController.php
- app/Http/Middleware/SetProjectInSession.php
This PR is submitted to comment ray() statements.
As ray() statements are very useful for development and debugging, I would recommend to comment them instead of removing them.
---
Screen shots for staging env:
> Comment Ray Statements

- app/Http/Controllers/GenericDashboardController.php
- database/procedures/generate_dashboard_summary.sql
- resources/js/components/MainDashboard.vue
- resources/views/generic-dashboard/dashboard.blade.php
This PR is submitted to fix #296 
---
**Comment edited on 2025-01-16**
It is now ready for review.
It contains below changes:
> Enhance Dashboard
