stats4sd/aec_portfolio

- app/Http/Controllers/Admin/Operations/AssessOperation.php
- app/Http/Controllers/Admin/Operations/RedlineOperation.php
- app/Http/Controllers/Admin/ProjectCrudController.php
- app/Models/Project.php
- public/assets/js/admin/forms/project_assess.js
- resources/views/projects/show.blade.php
Add basic project review page:
- All projects now have a "preview" option from the main list page. 
- The preview shows the key project details at the top, and a table for the principle ratings, which shows:
- the score;
- comments;
- the count of shared examples / indicators;
- the count of custom examples / indicators;
Clicking on either count opens a modal that lists the selected (or added) scoreTags / customScoreTags. 
The Ratings Total and Overall score is only displayed if the projects status is "Assessment Complete"
> Project table

- app/Enums/AssessmentStatus.php
- app/Http/Controllers/Admin/AssessmentCrudController.php
- app/Http/Controllers/Admin/Operations/RedlineOperation.php
- app/Http/Controllers/PrincipleAssessmentController.php
- app/Models/Assessment.php
- app/Models/PrincipleAssessment.php
- database/seeders/ProjectSeeder.php
- resources/js/components/AgroecologicalPrinciplesAssessment.vue
- resources/js/components/InitiativeListCard.vue
- resources/js/components/InitiativesList.vue
- resources/js/components/PrincipleAssessmentModal.vue
- resources/sass/_redline-radios.scss
- resources/sass/app.scss
- resources/views/projects/index.blade.php
- resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
- resources/views/vendor/backpack/crud/fields/redline_radio.blade.php
Updates to UX:
- adds filtering of initiatives;
- updates redlines to use "FAILED" status when needed;
- updates redline assessment UX;
- automatically removes custom tags with no name during save
- save actions now automatically refresh the root component, so you immediately see the rating on the main principle list view.
> Initiative list update

- app/Http/Controllers/AssessmentController.php
- resources/js/components/AgroecologicalPrinciplesAssessment.vue
- resources/js/components/PrincipleAssessmentModal.vue
Fixes #80; Fixes #79;
- Fixes '0' vs null issue by automatically assigning the value 0 to the principleAssessment object when the modal is opened.
- Fixes the "finalise" checkbox by setting a new assessmentComplete variable (it was not properly updating the DOM when the props.assessment.complete was updating)
- Fixes reference to principle_status on finaliseAssessment POST request.
> fixes for assessment process

- app/Http/Controllers/Admin/ProjectCrudController.php
- database/migrations/2023_06_27_131129_add_custom_conversion_ratio_to_projects_table.php
A small update - just the front-end section on the Initiatives creation page, so that the video guide can include the correct fields and information for adding the budget and currency to the initiatives.
> add front-end to currency conversion for video demo

- app/Exports/Assessment/RedlinesExport.php
- app/Http/Controllers/Admin/AssessmentCrudController.php
- app/Http/Controllers/Admin/RedLineCrudController.php
- app/Models/Assessment.php
- database/procedures/generate_dashboard_summary.sql
- resources/js/components/InitiativeListCard.vue
- resources/js/components/InitiativesList.vue
- resources/js/components/MainDashboard.vue
- routes/backpack/custom.php
This PR is submitted to solve issue #75.
Testing performed in local env with institutional admin and site admin respectively.
---
Changes made for below locations found for caption red line(s):
Initiatives > Filters
- Filter by Redline Status
- Redlines - Not Started
- Redlines - In Progress
- Redlines - Complete
- Redlines - Failed
Initiatives > Export All Initiative Data
- initiatives sheet > column R assessment_status > Redlines XXX
- redflag_assessment sheet
- redflag_assessment sheet > column I "redline_assessment_status"
Initiatives > Basic Info
- Access Redlines
Initiatives > Show More Info
- REDLINES
- Edit Redline Assessment
- Access Redlines
Dashboard > SUMMARY OF INITIATIVES
- Passed all redlines
Dashboard > SUMMARY OF RED FLAGS
- Red Lines
- Passed all redlines
> Change caption red line(s) to red flag(s)

- resources/js/components/AgroecologicalPrinciplesAssessment.vue
- resources/js/components/PrincipleAssessmentModal.vue
Minor PR - adds a subtle transition to the PrincipleAssessmentModal component. Previously, when you clicked "save and next" during the principle assessment it was not immediately obvious that the content had changed. This adds a small fade-out and in to make it easier to see that you have moved to the next principle in the list. 
Also added a max-width for styling on wider screens.
> Add transition to principle assessment modals

- app/Http/Controllers/Admin/ProjectCrudController.php
- to allow use of start date to get exchange rates for initiatives
- merging in quickly for recording. The only change is visual / ordering of questions in the initiatives creation screen.
> put start date before currency:

- app/Http/Controllers/ProjectController.php
- resources/js/components/InitiativesList.vue
This PR is submitted for fix issue #93.
It contains below changes:
1. Revise codes for filtering records, make sorting works when no filter applied
2. Add sortBy, sortDir in computed() function, make sorting works when any filter applied
3. Complete resetFilters() function, make Reset button works
4. Sort initiatives records by name in ascending order, which match the default value of sortBy and sortDir
5. Special handling for Reset button when there is a portfolio specified in GET parameter
> Fix initiative sorting

- resources/js/components/MainDashboard.vue
This PR is submitted to fix issue #95.
This is considered as an enhancement for more intuative UI/UX.
---
Screen shots:
Enter dashboard, summary data showed for all portfolios
Select a portfolio, summary data showed for selected portfolio
Select another portfolio, summary data showed for another selected portfolio
Reset Filters, summary data showed for all portfolios
> Dashboard get summary when change portfolio

- app/Http/Controllers/GenericDashboardController.php
- resources/js/components/InitiativeListCard.vue
- resources/js/components/MainDashboard.vue
This PR is submitted to fix issue #98 and #99.
It contains below changes:
1. Dashboard, show error message returned from database stored procedure
2. Dashboard, show error message if there is no fully assessed initiative, Overall score and AE budget are showed as "N/A"
3. Fix a minor typo in InitiativeListCard.vue: "Assess Principles" button instead of "Assess Red Flags" button.
Screen shot:
BEFORE
AFTER
> Dashboard error handling

- app/Http/Controllers/GenericDashboardController.php
This PR is submitted to fix issue #118.
According to user discussion in demonstration meeting on 2023-06-26, users suggested to sort principles by principle numbers in dashboard.
This will ease user to compare principles of different portfolios.
---
Screen shots:
BEFORE:
AFTER:
> Dashboard, sort principles by principle number 

- database/procedures/generate_dashboard_summary.sql
- database/procedures/remove_incomplete_dashboard_assessment.sql
In principle summary, all principles assessed in latest assessments are included even assessment.redline_status is not Complete.
This is not common, but it could happen for below scenario:
After principle assessment, user can assess red flag and change any red flag to YES to have 0 score.
This PR is submitted to exclude any latest assessments if it's redline_status is not Complete.
---
Screen shots:
A portfolio has two initiative. The first initiative has failed red flags assessment.
BEFORE:
Last assessments of both two initiatives are included in principle summary.
AFTER:
The first failed initiative is excluded from principle summary. Only the second Complete assessment is included in principle summary.
> Enhance Dashboard

- database/migrations/2023_07_12_140706_set_default_has_additional_criteria_to_zero_for_organisations_table.php
When reviewing PRs today, I noticed that the seeders were failing when creating organisations. It looks like there was no default set for `has_additional_criteria`, and the seeders were written before we added that. 
This tiny PR fixes this, so now `php artisan migrate:fresh --seed` runs smoothly again for testing purposes.
> Set defaults for org table

- resources/js/components/AgroecologicalPrinciplesAssessment.vue
- resources/js/components/PrincipleAssessmentModal.vue
This PR fixes #80, fixes #123. 
- the completion status is now explicitly set instead of being linked to the computed "has_rating" property (the computed property wasn't triggering the re-render of the parent). 
- the completion status and setting of "null" values to 0 all now occurs in the `save()` method. Previously the `null -> 0` was happening only during the initial mounting, so only worked for the first principle.
> Principle Assessment workflow tweaks

- .env.example
- app/Http/Controllers/Admin/ProjectCrudController.php
- app/Http/Controllers/GeneratePdfFileController.php
- config/services.php
- routes/backpack/custom.php
Browsershot was previously not running the JavaScript correctly to produce the chart in the pdf. 
A post from back in 2020 suggested that this is an issue with using `Browsershot::html()`, but it works with `Browsershot::url()`. 
So this PR moves to using `url()`, and adds the needed infrastructure to allow the headless Chrome instance to authenticate via http basic auth. Unfortuantely this means that we can't use the user's own account to authenticate, but given they need to be authenticated to even trigger the browsershot method, I think this is ok. 
I've added a TODO item to double check the security of the initiative show info page after these changes.
> browsershot-test: url instead of html

- app/Jobs/GetHistoricExchangeRates.php
This PR fixes #110.
Performed testing in local env for year 2011 and year 2012.
2012-01-01 exchange rate data has been retrieved once only.
> Get exchange rate data for one year inclusively from free currency API

- app/Http/Controllers/Admin/InstitutionTypeCrudController.php
- app/Http/Controllers/Admin/OrganisationCrudController.php
- app/Http/Controllers/Admin/PortfolioCrudController.php
- app/Http/Controllers/Admin/ProjectCrudController.php
- app/Http/Controllers/OrganisationController.php
- app/Http/Requests/OrganisationRequest.php
- app/Http/Requests/PortfolioRequest.php
- app/Http/Requests/ProjectRequest.php
- app/Models/InstitutionType.php
- app/Models/Organisation.php
- app/Models/User.php
- database/factories/OrganisationFactory.php
- database/factories/PortfolioFactory.php
- database/migrations/2023_07_18_104722_create_institution_types_table.php
- database/migrations/2023_07_18_105214_add_extra_details_to_organisations_table.php
- database/migrations/2023_07_18_105223_add_extra_details_to_portfolios_table.php
- database/seeders/DatabaseSeeder.php
- database/seeders/InstitutionTypeSeeder.php
- database/seeders/TestSeeder.php
- resources/js/app.js
- resources/js/components/InstitutionSettings.vue
- resources/js/institutions.js
- resources/views/organisations/portfolios.blade.php
- resources/views/organisations/show.blade.php
- resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
- routes/backpack/custom.php
- routes/web.php
- vite.config.js
fixes #146.
This PR adds the required extra information to portfolios and organisations, as per the technical specification.
- The database + seeders / factories are updated with the new fields
- The portfolio table view now includes budget and geographic reach
- Creating / editing portfolios via the CRUD panel controller has the extra fields:
- NOTE: I chose to only allow portfolio budgets in the institution's default currency, for simplicity. Given we do not have a clear start date for a portfolio (as with an initiative), I don't know how much sense it would be to give a single exchange rate for conversion. If this becomes an issue,  I think it is a V2.0 feature. 
- Editing institution details is now via a Vue component, and includes the extra relevant fields. 
- Users without the "edit …
> Extra institution + portfolio details

- app/Http/Controllers/Admin/AssessmentCrudController.php
- app/Http/Controllers/Admin/Operations/RedlineOperation.php
- app/Http/Controllers/Admin/Traits/UsesSaveAndNextAction.php
- app/Http/Controllers/AssessmentController.php
- public/assets/js/admin/forms/project_redlines.js
- public/assets/js/admin/forms/redlines.js
- resources/js/components/AgroecologicalPrinciplesAssessment.vue
- resources/sass/app.scss
- resources/views/vendor/backpack/crud/operations/redline.blade.php
This PR addresses a request to include a link to continue the next stage of the assessment within the current assessment:
- a new save option is added: "Save and start principle assessment"
This is done by overwriting the default save options within Backpack. Instead, the buttons are included directly in the `redline.blade.php` template. 
- NOTE: the new button is not technically a submit button, but it is linked to some javascript that will update the `_redirect` input value before submitting the form.
- the `_redirect` value is used in the redirect after saving, with a default set in case something goes wrong.
Similar to the red flags, a new option is added to take the user directly to the additional criteria assessment page. This option only appears when the organisation has additional …
> add 'next assessment stage' buttons to red flags and principles

- app/Providers/TelescopeServiceProvider.php
This PR allows site admins to review the Laravel Telescope logs in production environments.
> enable telescope in production for site admins

- app/Models/Assessment.php
fixes #156.
The issue was that the PDF generation doesn't use the current session, so there is no selected organisation. The assessment calls the `project` relationship to check for the existence of additiopnal criteria. It was failing to find the project because of the global scope. 
This PR removes the global scope from the relationship call. It doesn't affect other parts because it's assumed that once you have access to the assessment, you should always be able to access the parent project.
> Remove global scope from relationship call

- app/Http/Controllers/Admin/AdditionalCriteriaCrudController.php
- resources/views/organisations/additional-criteria.blade.php
This PR updates the additional criteria crud by:
- renaming the 'review' button as 'view'
- removing the extra save actions to just have 'save and back'
fixes #163
> edits button label and removes save operations

- app/Http/Controllers/OrganisationController.php
- resources/js/institutions.js
- resources/views/organisations/show.blade.php
- resources/views/vendor/backpack/base/inc/menu.blade.php
- routes/backpack/custom.php
This PR fixes #162, by updating the Session cache storage with the user's current tab. 
Previously, when returning to the My Institution page, the app would always reset to the Portfolios tab unless you specifically included a # in the url. This was particularly confusing when returning from any Additional criteria page, but more generally it's a nicer experience if the user goes back to the same place they left when returning to the page. 
This PR adds to the page's JS to retrieve the stored tab ONLY if there is no # in the url (to allow the user or custom links to overwrite it). It also sends an ajax request when the user changes tabs to update the sesson storage on the server.
> On the My Institution page, store the user's tab in Session for later

- app/Http/Controllers/Admin/Operations/RedlineOperation.php
- app/Http/Controllers/GenericDashboardController.php
- database/procedures/generate_dashboard_summary.sql
- resources/js/components/InitiativeListCard.vue
- resources/views/projects/show.blade.php
This fixes #186. Fixes #174 
This PR makes 3 visual changes in the same theme of "completion status".
According to the tool, assessments that fail the red flags should be considered "complete". This PR updates the system so that assessments with failed red flags:
- show the "show information" button on the list view;
- do *not* show the spider diagram on the show initiatives page;
- *are* included in the overall_score on the dashboard. 
- previously, they were not included, so the overall score did not take those 0% values into account in the score or the AE directed budget. 
They are still not included in the principle assessment dashbaord tab.
(2 initiatives in the selected portfolio, 1 = failed red flags; other = ~57% score
> Update system to include projects that failed all red flags as "completed"

- database/factories/PortfolioFactory.php
1 line change to update the database seeder based on the portfolio table structure change. FIxes issue when running `migrate:fresh`.
> (MINOR) Fix the db seeders after portfolio database structure change

- app/Http/Controllers/Admin/RevisionCrudController.php
- app/Http/Requests/RevisionRequest.php
- app/Models/Revision.php
- app/Models/User.php
- resources/js/components/PrincipleAssessmentModal.vue
- resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
- routes/backpack/custom.php
This PR fixes #148 .
Note: This PR is not fully functioning yet. This is submitted as a progress update.
It provides a Revision CRUD panel. It is accessible via url now. (/admin/revision)
I will add it to sidebar for site admin and site manager in another PR.
As revision CRUD panel users (site admin and site manager) will not change anything in revision records. This CRUD panel is ready-only.
---
It shows below changes of user selected institution:
1. Institution ID (show for testing purpose temporary, will be removed soon)
2. Initiative name
3. Item type: Red Flag / Principle / Additional Criteria
4. Item: The name of corresponding Red Flag / Principle / Additional Criteria
5. Key: Which value has been changed. e.g. Red flag value / Principle rating / Principle is_na / Additional …
> Add Revision CRUD

- app/Http/Controllers/GenericDashboardController.php
- database/procedures/generate_dashboard_summary.sql
- resources/js/components/MainDashboard.vue
- resources/js/radarChart.js
- resources/views/projects/show.blade.php
This PR addresses an issue highlighted by Emile, where there is no visual indication of principles that were marked as NA. 
Currently, 
- in the Initiative Show page, an "na" cannot be differentiated from a '0' in the spider chart, which is incorrect.
- in the Dashboard principles chart, there is no indication of how many initiatives marked a principle as "na". So one principle's summary might be based on 50 initiatives, while the next principle is based on 40 initiatives, and there is no visual to indicate this difference. 
Carlos suggested an improvement for the dashboard in the attached - adding a thin grey bar over the top of the main block colours for each principle to show the % of initiatives that marked the item as NA. This PR adds those bars, along with a description below the …
> Add visuals to represent NA principles

- app/Models/Project.php
- database/factories/ProjectFactory.php
- database/seeders/ProjectSeeder.php
- public/assets/js/admin/forms/project_create.js
This PR fixes #198, fixes #191.
When an initiative's currency is the same as the organisation's default, the exchange_rate entry field is hidden, and instead the exchange_rate is set to 1. This was being done at the database level. This meant that the PHP code to calculate the budget_org field did not have that information, and so was multiplying by null. 
This PR fixes that to always send a value for the exchange rate through the CRUD panel when creating or editing a project, so that the budget_org calculation runs correctly. 
Turns out the sorting wasn't actually working at all, as it was sorting `initiatives` instead of `filteredInitiatives`. This PR fixes that issue, and also sets the budget sorting to work with `budget_org` instead of `budget` (as `budget` may be in different …
> Budget checks

- app/Http/Controllers/Admin/HelpTextEntryCrudController.php
- app/Models/HelpTextEntry.php
- app/Providers/AppServiceProvider.php
- app/View/Components/HelpTextEntry.php
- database/migrations/2023_08_04_113912_create_help_text_entries_table.php
- database/seeders/HelpTextEntrySeeder.php
- database/seeders/RoleSeeder.php
- package-lock.json
- package.json
- resources/js/app.js
- resources/js/components/InitiativeListCard.vue
- resources/js/components/InitiativesList.vue
- resources/js/components/InstitutionSettings.vue
- resources/js/components/MainDashboard.vue
- resources/js/components/PrincipleAssessmentModal.vue
- resources/js/components/vHelpTextEntry.vue
- resources/js/components/vHelpTextLink.vue
- resources/sass/app.scss
- resources/views/components/help-text-entry.blade.php
- resources/views/components/help-text-link.blade.php
- resources/views/generic-dashboard/dashboard.blade.php
- resources/views/organisations/members.blade.php
- resources/views/organisations/portfolios.blade.php
- resources/views/organisations/show.blade.php
- resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
- routes/backpack/custom.php
This PR adds the capacity for us to quikly add help text to anywhere within the application. 
Instead of hard-coding the help text into the pages, I wanted to do 2 things:
1. Make it quick for us to add new help text anywhere in the system.
2. Allow Site Managers / Admins to edit the text shown from the admin panel. 
The first is achieved through a pair of blade components and vue components - I made both so we can use them on blade/php rendered pages and within Vue component pages. 
- the `x-help-text-link` and `v-help-text-link` components display a `?` symbol, and when clicked on *either* show the corresponding `x-help-text-entry` / `v-help-text-entry` collapsible component, *or* show a popover. The collapse is the default, and you can make it a popover by adding the attribute …
> Adds Help Text Helper + Guidance throughout system

- app/View/Components/HelpTextLink.php
- database/migrations/2023_08_08_101457_set_rating_to_1dp_in_principle_assessment_table.php
- resources/sass/_print-tweaks.scss
- resources/views/components/help-text-link.blade.php
- resources/views/projects/show.blade.php
PR to fix #197:
- removed duplicate budget entry when the initiative's budget is the same as the organisation's.
- changed the layout to highlight the overall score more prominently, and add explanation of the score with help text.
- modified the print layout so that the principle summary appears on a new page with a title. 
- hidden the principle summary table if the main principle assessment is not complete (e.g. if the red flags were failed).
Also added a minor fix so that the blade help-text-link can now also act as a popover.
> Review init review

- app/Http/Controllers/ProjectController.php
- database/factories/ProjectFactory.php
- database/seeders/DatabaseSeeder.php
Fixes #190.
Minor PR to set the correct default initiative sort settings when there is nothing in the Session storage. Previously the sorting and sort direction were set to 0, which meant there was no selected sort-by and the sort direction didn't work until you hit reset.
Also updated the project factory so the created_at for generated projects is randomised. I used this to check the created_at sort, which works correctly 👍.
> Review initiative sorting

- app/Http/Controllers/Admin/AdditionalCriteriaCrudController.php
- app/View/Components/HelpTextLink.php
- database/migrations/2023_08_08_101457_set_rating_to_1dp_in_principle_assessment_table.php
- database/seeders/RoleSeeder.php
- resources/sass/_print-tweaks.scss
- resources/views/components/help-text-link.blade.php
- resources/views/projects/show.blade.php
This PR fixes #203:
- updated RoleSeeder to add the `view portfolios` to institutional members, and remove the `maintain custom principles`.
- Updated the AdditionalCriteriaCrudController to deny access to create/update/delete operations unless you have the `maintain custom principles` permission. 
- even though we were hiding the buttons on the main My Institution page, you could still click through to "View", then the edit + delete options were shown on that page. With this update, those buttons no longer show. 
NOTE: This PR includes PR #210, because my local version started expecting the View Component class for x-help-text-link added in that PR. I recommend not reviewing this one until 210 is merged in, so then the changes made here will be much more clear. 
ALSO NOTE: Institutional …
> Fix Members permissions

- app/Console/Commands/GetExchangeRatesForOneDay.php
- app/Console/Kernel.php
- app/Http/Controllers/ExchangeRateController.php
- app/Jobs/GetOneDayExchangeRates.php
- app/Providers/AppServiceProvider.php
This PR is submitted to fix #124.
Freecurrency API provides exchange rate data up to yesterday, consider time difference and time zones, reserve more buffer to get data of the date before yesterday instead of yesterday.
Command:
php artisan app:get-daily-exchange-rates
The schedule job will be executed at 00:21 AM everyday.
---
I intended to modify GetHistoricExchangeRates.php to support this feature. But I realised that this class cannot have another constructor method with different parameters. Finally I copy it as GetOneDayExchangeRates.php.
> Get One Day Exchange Rates Data

- app/Http/Controllers/ProjectController.php
- resources/js/components/InitiativeListCard.vue
- resources/js/components/InitiativesList.vue
- resources/js/components/vHelpTextLink.vue
- resources/views/projects/index.blade.php
The issue: On the initiative list page, the new help-text items were sending ajax requests to retrieve the correct text from the database. But it was causing 2 ajax requests per initiative card, all retrieving the same data. 
This PR is a quick hack to manually retrieve those HelpTextEntry items as part of the initial page load, and pass them down into the Vue components, thus avoiding the un-needed ajax requests.
> FIX: Get help text only once for initiative cards

- resources/js/components/InitiativesList.vue
FIxes delete initiative option that was broken in merging a while back.
> re-add removeInitiative event handler

- database/seeders/DashboardRatingSeeder.php
I found a bug in dashboard when I am doing testing in my local Linux env.
For a newly created portfolio with a newly created project, I assess red flag and principles with score 1.9 or 2.0.
In dashboard, the principle summary for this portfolio not showing rating properly.
I suspect there may be something different about stored proc / function deployment in database in docker image....
P.S. I manually deployed stored proc / function in TablePlus due to permission issue before...
I did same testing in local Windows env, but it works properly. Principle summary can be showed correctly.
Suddenly I recall that dashboard_rating.max_rating for GREEN record needs to change to a value > 2.0, e.g. 2.01.
This is to include principles scored 2.0. I update it in TablePlus then principle rating works …
> Fix Principle Rating Issue in Dashboard

- app/Http/Controllers/Admin/OrganisationCrudController.php
- app/Models/Organisation.php
- database/migrations/2023_11_01_112340_add_column_to_organisations_table.php
This PR is submitted to fix issue #234.
This PR contains below change:
1. organisations table, add a boolean column "contributes_to_funding_flow"
2. Admin Panel > Organisation CRUD, create/edit view, add checkbox for a flag to show if it contributes to funding flow analysis
---
Screen shot:
> Add Funding Flow Analysis Flag in Organisation

- app/Models/InitiativeCategory.php
- app/Models/InstitutionType.php
When "reordering" institution types on the admin panel (`/admin/institution-type`), the order set in re-ordering was not reflected in how they are displayed throughout the site. 
This PR fixes that issue by adding an `orderBy` global scope. 
It does the same for `InitiativeCateogry`.
> always order institution types by admin-set ordering

- app/Models/Assessment.php
Bug report from user - when accessing the main organisation's 'show' page, they get a 500 error "division by zero". 
Stack trace showed this as coming from the `Assessment` class => `getAdditionalScoreAttribute()`. It was assuming there was at least 1 additional criteria, even though the organisation in question doesn't have any. 
I added a check to make sure the organisation is using additional criteria and that there is at least 1 additionalCriteria entry for the organisation to fix the issue. 
**Screenshot**
> FIX: skip division if no additional criteria exist

- app/Models/Assessment.php
The stack-trace on this one was odd. It looks like the system was trying to json_serialise an empty assessment? So there was no project (because there was no data yet), but it was still trying to calculate the variables defined in `$appends`. 
I have no idea why, but making the project optional with `?` works. Now, if there is ever *not* a project set, the additional_score attribute will return null.
> fix for odd telecope-y bug?

- app/Mail/AddMemberConfirmed.php
- app/Models/Organisation.php
- resources/views/emails/invite.blade.php
- resources/views/emails/invite_confirmed.blade.php
There is a minor change to add a flag to indicate "contribute to funding flow" in portfolio level.
The program change is committed to dev branch accidentally.
This minor change will be reviewed when we create a PR for live env deployment. That PR will include all delta changes between dev branch and main branch.
---
This PR is submitted to add existing user to institution directly.
This PR contains below changes in backend:
1. For email address not existed in existing users, use original workflow to send email invitation.
2. For email address that existed in existing users, do below if user not belong to the institution
2.1 Send email confirmation instead of email invitation, it is not required to register again
2.2 Add role_invites record for reference purpose
2.3 Add …
> Add Existing User to Institution Directly

- database/procedures/generate_dashboard_summary.sql
This PR is submitted for fix #244.
This PR contains one change:
1. Dashboard, to exclude initiatives in portfolios that are not contributing to funding flow
---
In dashboard, we get initatives regardless whether it's portfolio is contributing to funding flow or not.
I assume it will be the default way for getting initiatives in dashboard for comparison. Therefore I added a condition in stored procedure related SELECT SQL directly. If we add a new filter in dashboard Vue component, user will need to select it everytime.
Um... probably we can add a new filter selection box, with 3 options:
1. Contribute to funding flow
2. Not contribute to funding flow
3. All
I am not quite sure whether it will increase complexity and create possible confusion. So... I stick with the current approach first.
> Dashboard - Exclude Non Funding Flow Initiatives

- .env.example
- app/Console/Commands/GetExchangeRatesForOneDay.php
- app/Jobs/GetOneDayExchangeRates.php
- app/Models/SystemLog.php
- app/Services/DBLog.php
- database/migrations/2024_03_11_104041_create_system_logs_table.php
This PR is submitted to help resolving issue for exchange rate retrieval.
1. Add log message in database level to trace program executed by schedule job and queue
2. Add configuration in .env, make it flexible to turn on / turn off database log feature
---
Testing in local env:
When QUEUE_CONNECTION=sync
- only first 5 currencies exchange rate retrieved (33 * 5 = 165 records).
- no new records in jobs table
When QUEUE_CONNECTION=database
- system_logs table is empty
- jobs table is empty
- at the beginning, handle first 5 currencies
- after each minute, handled another 5 currencies
- finally 33 currencies exchange rate data retrieved (33 * 33 = 1089)
---
Possible casue in live env:
- 1650 jobs accumulated (1650 / 33 = 50 days), we may need to clear all jobs …
> Add Database Log

- app/Http/Controllers/GenericDashboardController.php
This PR is submitted to fix an uinexpected message in dashboard.
Root cause identified:
Incorrect column used in query. In whereIn() clause, the column should be "project_id" instead of "id".
The fix has been applied to both $allAssessmentsYours and $allAssessmentsOthers.
```
$allAssessmentsYours = $allAssessments->whereIn(
'project_id',
DB::table('dashboard_project')
->select('project_id')
->where('dashboard_id', $dashboardYoursId)
->get()
->pluck('project_id')
->toArray()
);
```
---
Screen shots
BEFORE:
AFTER:
> Fix Dashboard Unexpected Message

- resources/js/components/UserFeedbackForm.vue
- resources/views/organisations/portfolios.blade.php
This PR is submitted to fix #265
1. If the "anonymise" option is ticked, column user_feedbacks.user_id should be null. To make sure we are doing what we do.
- I cannot replicate this issue in local env. column user_feedbacks.user_id is null when "anonymise" option is ticked
- Maybe we have this bug in early stage, and then we fixed it but it has not been deployed to live env yet
2. By default, user support request should untick the "anonymise" option.
3. My Institution > Portfolio > Help text for "Institution Portfolios", we should show the help text all the time. To increase the possibility that user to read it.
---
Screen shots:
> Fix User Support Issue

- .gitignore
- app/Http/Controllers/Admin/ProjectCrudController.php
- app/Http/Requests/ProjectRequest.php
- app/Models/Assessment.php
- app/Models/PrincipleAssessment.php
- database/migrations/2018_08_08_100000_create_telescope_entries_table.php
- database/seeders/TestSeeder.php
- resources/js/components/InitiativeListCard.vue
- resources/js/components/InitiativesList.vue
- routes/backpack/custom.php
fixes #274. 
This PR add the option for users to duplicate a project and all associated assessments/entries. This is to address times when a project gets an extension, and the user wants to associate the new budget with the date of the extension and not the date of the project start. 
The duplicate function does the following:
- clones the Project entry;
- associates the clone with the Continent, Region and Country models from the original;
- clones all FundingSource entries that are linked to the original;
- clones all Assessment entries that are linked to the original.
For each new assessment:
- the cloned assessment is linked to the Redline, Principle and AdditionalCriteria; and all pivot values are copied over to ensure the cloned assessment results are identical. 
- the clones …
> Add duplicate initiative feature

- app/Console/Commands/ClonePortfolio.php
Adds a small command that clones an entire portfolio (projects, assessments). 
It uses the existing duplicate function for individual projects, and loops through a full list of portfolios. 
The result is a new portfolio with an identical name except with " (clone)" added to it; and the project names and codes also have " (clone)" and "-clone" appended to them. 
This is only for specific use cases and should only be accessible by system admins through the CLI.
> add cloning command for portfolios

- app/Exports/InitiativeImportTemplate/InitiativeImportTemplateExportSheet.php
This PR is submitted to fix #291 
1. Add new column "exchange_rate_eur" in excel template file for importing projects
2. Shift validations to corresponding columns after adding new column at column G
The static excel template file "storage\app\Agroecology Funding Tool - Initiative Import Template.xlsx" is reference only. 
This is no longer being used when downloading the excel template file for importing projects.
---
I thought we are using static excel template file in PR #251, while it has been changed to generate excel template file programmatically in PR #247
> Update Excel Template File for Importing Projects

- app/Http/Controllers/Admin/ProjectCrudController.php
- resources/sass/_backpack-form-tweaks.scss
This PR is submitted to fix #276 
It is not yet ready for review. It is submitted for progress review.
---
As per our discussion this morning, there are 2 approaches. We will go for approach 2.
1. Change background color of all required fields in all forms. Including portfolio creation, project creation, principle assessment, etc.
2. Find CSS class for required field, update CSS class to have light yellow background color. So that all required fields will have different background color by one change.
---
---
This PR is revised to contain below changes now:
> Enhance Required Fields

- resources/js/components/PrincipleAssessmentModal.vue
This PR is submitted to fix #170 
After digesting Emily's suggestion, I tried to make a comprimise to minimize program change.
---
This PR should contain below changes:
---
TODO: review VueJS fundamentals
---
Screen shots:
> Improve Principle Assessment UI

- app/Console/Commands/RegenerateTeamLevelRoleRecords.php
- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/SelectedOrganisationController.php
- app/Http/Kernel.php
- app/Http/Middleware/SetOrgForPermissions.php
- app/Http/Middleware/TeamsPermission.php
- app/Models/Organisation.php
- app/Models/User.php
- config/permission.php
- database/migrations/2025_01_16_113418_add_teams_fields.php
- database/seeders/DatabaseSeeder.php
- database/seeders/TestSeeder.php
- resources/views/auth/register.blade.php
- resources/views/vendor/backpack/base/inc/menu.blade.php
- routes/backpack/custom.php
This PR is submitted to fix #242
It should contain below changes:
> Add Team Level Role

- app/Console/Commands/RegenerateTeamLevelRoleRecords.php
- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Middleware/EnsureOrganisationIsSelected.php
- routes/backpack/custom.php
This PR is submitted to fix some global role issues.
Some more issues for team-level roles found...
---
> Fix Global Role Issues

- app/Http/Controllers/Admin/ProjectCrudController.php
- app/Http/Requests/ProjectRequest.php
- database/migrations/2025_03_04_125842_make_main_recipient_text_in_projects_table.php
This PR fixes #310, and makes some updates to validate the funding sources. (Fixes #295).
- Updates `projects.main_recipient` to be a text instead of varchar;
- Adds validation rules for the 3 fields inside the "fundingSources" relationship repeater. 
- adds a max-character validation to `main_recipient`, `name`, `code`, `description`, `fundingSources.*.source`
- adds max int value validation (just for completeness).
> Update Validation in project creation.
